name: erpsystems
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets: 
    - Assets/login.png
    - Assets/Icon/Message.png
    - Assets/Icon/Lock.png
    - Assets/Icon/DashboardActive.png
    - Assets/Icon/DashboardInactive.png
    - Assets/Icon/SalesActive.png
    - Assets/Icon/SalesInactive.png
    - Assets/Icon/PurchasingActive.png
    - Assets/Icon/PurchasingInactive.png
    - Assets/Icon/FinanceActive.png
    - Assets/Icon/FinanceInactive.png
    - Assets/Icon/WarehouseActive.png
    - Assets/Icon/WarehouseInactive.png
    - Assets/Icon/HRActive.png
    - Assets/Icon/HRInactive.png
    - Assets/Icon/AnalyticsActive.png
    - Assets/Icon/AnalyticsInactive.png
    - Assets/Icon/DocumentActive.png
    - Assets/Icon/DocumentInactive.png
    - Assets/Icon/SettingActive.png
    - Assets/Icon/SettingInactive.png
    - Assets/Icon/Logout.png