name: erpsystems
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  autocomplete_textfield: ^2.0.1
  date_time_picker: ^2.1.0
  easy_autocomplete: ^1.6.0
  fl_chart: ^0.66.0
  flutter:
    sdk: flutter
  flutter_custom_month_picker: ^0.1.3
  flutter_month_picker: ^0.0.2
  flutter_screenutil: ^5.9.0
  flutter_typeahead: ^5.0.2
  get: ^4.6.6
  get_storage: ^2.1.1
  http: ^1.2.0
  intl: ^0.17.0
  percent_indicator: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets: 
    - Assets/login.png
    - Assets/Icon/Message.png
    - Assets/Icon/Lock.png
    - Assets/Icon/DashboardActive.png
    - Assets/Icon/DashboardInactive.png
    - Assets/Icon/SalesActive.png
    - Assets/Icon/SalesInactive.png
    - Assets/Icon/PurchasingActive.png
    - Assets/Icon/PurchasingInactive.png
    - Assets/Icon/FinanceActive.png
    - Assets/Icon/FinanceInactive.png
    - Assets/Icon/WarehouseActive.png
    - Assets/Icon/WarehouseInactive.png
    - Assets/Icon/HRActive.png
    - Assets/Icon/HRInactive.png
    - Assets/Icon/AnalyticsActive.png
    - Assets/Icon/AnalyticsInactive.png
    - Assets/Icon/DocumentActive.png
    - Assets/Icon/DocumentInactive.png
    - Assets/Icon/SettingActive.png
    - Assets/Icon/SettingInactive.png
    - Assets/Icon/Logout.png
    - Assets/Icon/Search.png
    - Assets/Icon/Profile.png
    - Assets/Icon/Attandance.png
    - Assets/Icon/Absent.png
    - Assets/Icon/Late.png
    - Assets/Icon/Leave.png
    - Assets/Icon/Customer.png
    - Assets/Icon/Shipping.png
    - Assets/Icon/Payment.png
    - Assets/Icon/Term.png
    - Assets/Icon/Product.png
    - Assets/Icon/Packaging.png
    - Assets/Icon/Flag.png
    - Assets/Icon/Settings.png
    - Assets/Icon/addTarget.png
    - Assets/Icon/addTargetYear.png
    - Assets/Icon/CalendarIcon.png
    - Assets/Icon/ShipmentIcon.png